version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app
    environment:
      - DJANGO_SETTINGS_MODULE=LearnSpider.settings
    command: python manage.py runserver 0.0.0.0:8000