# Generated by Django 5.0.7 on 2025-02-16 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        blank=True, help_text="类别名", max_length=200, null=True
                    ),
                ),
                (
                    "detail",
                    models.CharField(
                        blank=True,
                        default=None,
                        help_text="类别的描述",
                        max_length=200,
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "sd_ls_category",
            },
        ),
        migrations.CreateModel(
            name="NewsCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("name", models.CharField(max_length=100)),
                ("slug", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "sd_ls_news_category",
            },
        ),
        migrations.CreateModel(
            name="NewsPlatform",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "db_table": "sd_ls_news_platform",
            },
        ),
        migrations.CreateModel(
            name="Topics",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "order_id",
                    models.PositiveIntegerField(
                        blank=True,
                        default=3,
                        help_text="题目排序，根据难度分排序，会变",
                        null=True,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        default=None,
                        help_text="题目的标题，最好有趣个性化一点",
                        max_length=200,
                    ),
                ),
                (
                    "detail",
                    models.TextField(
                        blank=True,
                        default="暂无表述",
                        help_text="题目的描述：简单创造一个背景故事",
                        null=True,
                    ),
                ),
                (
                    "goal",
                    models.TextField(
                        blank=True,
                        default="暂无描述",
                        help_text="题目的目标：掌握xxx",
                        null=True,
                    ),
                ),
                (
                    "question",
                    models.TextField(
                        blank=True,
                        default="暂无题目要求",
                        help_text="题目要求",
                        null=True,
                    ),
                ),
                (
                    "answer",
                    models.CharField(
                        blank=True, help_text="题目的答案", max_length=255, null=True
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        default="成神之路",
                        help_text="题目类别：成神之路，xpath特训",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("beginner", "初级"),
                            ("intermediate", "中级"),
                            ("advanced", "高级"),
                            ("ultimate", "终极"),
                        ],
                        default="简单",
                        help_text="难度",
                        max_length=12,
                        null=True,
                    ),
                ),
                (
                    "difficulty_score",
                    models.BigIntegerField(
                        blank=True,
                        default=200,
                        help_text="难度分数，后续根据此字段排序order_id",
                        null=True,
                    ),
                ),
                (
                    "points",
                    models.TextField(
                        blank=True,
                        default="暂未更新考点",
                        help_text="本题的考点",
                        null=True,
                    ),
                ),
                (
                    "published",
                    models.BooleanField(
                        blank=True, default=False, help_text="是否发布", null=True
                    ),
                ),
                (
                    "pass_status",
                    models.BooleanField(
                        blank=True, default=False, help_text="是否通过", null=True
                    ),
                ),
                (
                    "solution_txt",
                    models.URLField(
                        blank=True,
                        default="暂无表述",
                        help_text="题解，图文讲解",
                        null=True,
                    ),
                ),
                (
                    "solution_video",
                    models.URLField(
                        blank=True, default="暂无表述", help_text="视频讲解", null=True
                    ),
                ),
                (
                    "api_type",
                    models.CharField(
                        blank=True,
                        default="直接对应视图",
                        help_text="此题目的接口类型：直接对应视图，访问一个接口判断后决定是否返回视图，返回一个视图+【多个】api",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "api_prefix",
                    models.CharField(
                        blank=True,
                        default="topic/",
                        help_text="topic/,view/,api/",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "response_path",
                    models.TextField(
                        blank=True, help_text="题目路径【文件名】", null=True
                    ),
                ),
            ],
            options={
                "db_table": "sd_ls_topic",
                "ordering": ["order_id"],
            },
        ),
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("title", models.CharField(max_length=200)),
                (
                    "url",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("desc", models.CharField(blank=True, max_length=500, null=True)),
                ("publish_time", models.DateTimeField(blank=True, null=True)),
                ("timestamp", models.BigIntegerField(blank=True, default=0, null=True)),
                ("author", models.CharField(blank=True, max_length=255, null=True)),
                ("content", models.TextField()),
                ("hot", models.IntegerField(default=0)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="news",
                        to="topics.newscategory",
                    ),
                ),
                (
                    "platform",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="news",
                        to="topics.newsplatform",
                    ),
                ),
            ],
            options={
                "db_table": "sd_ls_news",
            },
        ),
        migrations.CreateModel(
            name="NewsRequestHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("request_time", models.DateTimeField(auto_now_add=True)),
                ("response_data", models.JSONField()),
                ("status", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "platform",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="topics.newsplatform",
                    ),
                ),
            ],
            options={
                "db_table": "sd_ls_news_request_history",
            },
        ),
        migrations.CreateModel(
            name="TopicCategoryRelation",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "display_order",
                    models.PositiveIntegerField(blank=True, default=100, null=True),
                ),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="topics.category",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="topics.topics"
                    ),
                ),
            ],
            options={
                "db_table": "sd_ls_topic_category_relation",
                "unique_together": {("topic", "category")},
            },
        ),
    ]
