# Generated by Django 5.0.7 on 2024-07-15 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0001_squashed_0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topics',
            name='order_id',
            field=models.PositiveIntegerField(blank=True, default=3, help_text='题目排序，根据难度分排序，会变'),
        ),
        migrations.AlterField(
            model_name='topics',
            name='title',
            field=models.CharField(blank=True, default='111', help_text='题目的标题，最好有趣个性化一点', max_length=200),
        ),
    ]
