# Generated by Django 5.0.7 on 2025-02-27 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("topics", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Web3NewsTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("name", models.CharField(max_length=200)),
                ("tag", models.CharField(max_length=200)),
                ("name_en", models.CharField(max_length=200)),
                ("url", models.CharField(blank=True, max_length=255, null=True)),
                ("desc", models.CharField(blank=True, max_length=500, null=True)),
                ("desc_en", models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                "db_table": "sd_ls_news_web3_tags",
            },
        ),
    ]
