# Generated by Django 5.0.7 on 2024-07-15 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0002_alter_topics_order_id_alter_topics_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='topics',
            name='response_path',
            field=models.TextField(blank=True, help_text='题目路径【文件名】', null=True),
        ),
    ]
