# Generated by Django 5.0.7 on 2025-02-27 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("topics", "0002_web3newstag"),
    ]

    operations = [
        migrations.CreateModel(
            name="Web3News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("title", models.CharField(blank=True, max_length=200, null=True)),
                ("sub_title", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "web_link",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("author_name", models.CharField(blank=True, max_length=50, null=True)),
                ("published_time", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "sd_ls_news_web3",
            },
        ),
        migrations.AddField(
            model_name="web3newstag",
            name="tag_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="web3newstag",
            name="name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="web3newstag",
            name="name_en",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="web3newstag",
            name="tag",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
