# Generated by Django 5.0.7 on 2024-07-16 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0003_topics_response_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topics',
            name='difficulty_score',
            field=models.BigIntegerField(blank=True, default=200, help_text='难度分数，后续根据此字段排序order_id'),
        ),
    ]
