# Generated by Django 5.0.7 on 2024-07-19 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0006_alter_topics_category_alter_topics_difficulty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topics',
            name='des',
            field=models.TextField(blank=True, default='暂无表述', help_text='题目的描述：简单创造一个背景故事', null=True),
        ),
        migrations.AlterField(
            model_name='topics',
            name='goal',
            field=models.TextField(blank=True, default='暂无描述', help_text='题目的目标：掌握xxx', null=True),
        ),
        migrations.AlterField(
            model_name='topics',
            name='order_id',
            field=models.PositiveIntegerField(blank=True, default=3, help_text='题目排序，根据难度分排序，会变', null=True),
        ),
        migrations.AlterField(
            model_name='topics',
            name='question',
            field=models.TextField(blank=True, default='暂无题目要求', help_text='题目要求', null=True),
        ),
    ]
