# Generated by Django 5.0.7 on 2024-07-24 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0015_topics_api_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='topics',
            name='api_prefix',
            field=models.CharField(blank=True, default='topic/', help_text='topic/,view/,api/', max_length=255, null=True),
        ),
    ]
