# Generated by Django 5.0.7 on 2024-07-25 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0016_topics_api_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='topics',
            name='answer',
            field=models.CharField(blank=True, default='666', help_text='题目的答案', max_length=255),
        ),
    ]
