# Generated by Django 5.0.7 on 2025-01-20 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("topics", "0018_topics_published"),
    ]

    operations = [
        migrations.AlterField(
            model_name="topics",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="topics",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
