# Generated by Django 5.0.7 on 2025-02-09 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("topics", "0019_alter_topics_created_at_alter_topics_updated_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.PositiveIntegerField(
                        blank=True, default=3, help_text="类别名", null=True
                    ),
                ),
                (
                    "detail",
                    models.CharField(
                        blank=True,
                        default=None,
                        help_text="类别的描述",
                        max_length=200,
                        null=True,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RenameField(
            model_name="topics",
            old_name="des",
            new_name="detail",
        ),
        migrations.AlterField(
            model_name="topics",
            name="title",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="题目的标题，最好有趣个性化一点",
                max_length=200,
            ),
        ),
        migrations.CreateModel(
            name="TopicCategoryRelation",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "display_order",
                    models.PositiveIntegerField(blank=True, default=100, null=True),
                ),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="topics.category",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="topics.topics"
                    ),
                ),
            ],
            options={
                "unique_together": {("topic", "category")},
            },
        ),
    ]
