# Generated by Django 5.0.7 on 2025-02-09 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "topics",
            "0020_category_rename_des_topics_detail_alter_topics_title_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelTable(
            name="category",
            table="sd_ls_category",
        ),
        migrations.AlterModelTable(
            name="topiccategoryrelation",
            table="sd_ls_topic_category_relation",
        ),
        migrations.AlterModelTable(
            name="topics",
            table="sd_ls_topic",
        ),
    ]
