# Generated by Django 5.0.7 on 2025-02-09 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("topics", "0021_alter_category_table_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                blank=True, help_text="类别名", max_length=200, null=True
            ),
        ),
    ]
