# Generated by Django 5.0.7 on 2025-02-11 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("topics", "0022_alter_category_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="topics",
            name="answer",
            field=models.CharField(
                blank=True, help_text="题目的答案", max_length=255, null=True
            ),
        ),
    ]
