# Generated by Django 5.0.7 on 2025-02-15 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("topics", "0024_newscategory_newsplatform_news"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="news",
            table="sd_ls_news",
        ),
        migrations.AlterModelTable(
            name="newscategory",
            table="sd_ls_news_category",
        ),
        migrations.AlterModelTable(
            name="newsplatform",
            table="sd_ls_news_platform",
        ),
    ]
