# Generated by Django 5.0.7 on 2025-02-15 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "topics",
            "0001_squashed_0025_alter_news_table_alter_newscategory_table_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="RequestHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("request_time", models.DateTimeField(auto_now_add=True)),
                ("response_data", models.JSONField()),
                ("status", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "platform",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="topics.newsplatform",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
