# Generated by Django 5.0.7 on 2025-02-15 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("topics", "0026_requesthistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="hot",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterModelTable(
            name="requesthistory",
            table="sd_ls_request_history",
        ),
    ]
