# Generated by Django 5.0.7 on 2025-02-15 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("topics", "0027_news_hot_alter_requesthistory_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newscategory",
            name="slug",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
