# Generated by Django 5.0.7 on 2025-02-16 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("topics", "0028_alter_newscategory_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="author",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="news",
            name="timestamp",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
