# Generated by Django 5.0.7 on 2025-02-16 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("topics", "0029_news_author_news_timestamp"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="desc",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
