# Generated by Django 5.0.7 on 2025-02-16 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("topics", "0030_news_desc"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="RequestHistory",
            new_name="NewsRequestHistory",
        ),
        migrations.AlterModelTable(
            name="newsrequesthistory",
            table="sd_ls_news_request_history",
        ),
    ]
